In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
rnrhof = pd.read_html('https://en.wikipedia.org/wiki/List_of_Rock_and_Roll_Hall_of_Fame_inductees')

In [4]:
print(f'Total tables: {len(rnrhof)}')

Total tables: 9

In [5]:
rnrhof_table = pd.read_html('https://en.wikipedia.org/wiki/List_of_Rock_and_Roll_Hall_of_Fame_inductees', match='Year')

In [6]:
len(rnrhof_table)

7

In [7]:
df = rnrhof_table[0]

In [8]:
df.drop(columns = ['Image'], inplace=True)

In [9]:
df.rename(columns={'Inducted by[5]': 'Inducted By', 'Inducted members':'Inducted Members', 'Year':'Induction Year'}, inplace=True)

In [10]:
df.dtypes

Induction Year       int64
Name                object
Inducted Members    object
Inducted By         object
dtype: object

In [11]:
df['Inducted By'] = df['Inducted By'].astype(str)
df['Inducted Members'] = df['Inducted Members'].astype(str)
df['Name'] = df['Name'].astype(str)

In [12]:
# df.loc[:,df['Inducted Members']].replace(np.nan,"Solo Artist", regex=True, inplace=True)

In [13]:
df.tail(50)

,Induction Year,Name,Inducted Members,Inducted By
189,2013,Public Enemy,"Flavor Flav, Professor Griff, Terminator X, an...",Harry Belafonte and Spike Lee
190,2013,Rush,"Geddy Lee, Alex Lifeson, and Neil Peart.[104]",Dave Grohl[N2] and Taylor Hawkins[N2]
191,2013,Donna Summer,nan,Kelly Rowland
192,2014,Peter Gabriel,nan,Chris Martin
193,2014,Hall & Oates,Daryl Hall and John Oates.[105],Questlove
194,2014,Kiss,"Peter Criss, Ace Frehley, Gene Simmons, and Pa...",Tom Morello
195,2014,Nirvana,"Kurt Cobain, Dave Grohl, and Krist Novoselic.[...",Michael Stipe[N3]
196,2014,Linda Ronstadt,nan,Glenn Frey[N3]
197,2014,Cat Stevens,nan,Art Garfunkel[N3]
198,2015,The Paul Butterfield Blues Band,"Paul Butterfield, Mike Bloomfield, Elvin Bisho...",Peter Wolf
199,2015,Joan Jett & the Blackhearts,"Joan Jett, Kenny Laguna, Gary Ryan, Lee Crysta...",Miley Cyrus
200,2015,Lou Reed[110],nan,Patti Smith[N3]
201,2015,Green Day,"Billie Joe Armstrong, Tr√© Cool, and Mike Dirnt...",Fall Out Boy
202,2015,Stevie Ray Vaughan and Double Trouble,"Stevie Ray Vaughan, Chris Layton, Tommy Shanno...",John Mayer
203,2015,Bill Withers,nan,Stevie Wonder[N3]
204,2016,Cheap Trick,"Bun E. Carlos, Rick Nielsen, Tom Petersson, an...",Kid Rock
205,2016,Chicago,"Peter Cetera, Terry Kath, Robert Lamm, Lee Lou...",Rob Thomas
206,2016,Deep Purple,"Ritchie Blackmore, David Coverdale, Rod Evans,...",Lars Ulrich[N3]
207,2016,N.W.A,"DJ Yella, Ice Cube, Dr. Dre, Eazy-E, and MC Re...",Kendrick Lamar
208,2016,Steve Miller,nan,The Black Keys
209,2017,Electric Light Orchestra,"Bev Bevan, Jeff Lynne, Richard Tandy, and Roy ...",Dhani Harrison
210,2017,Joan Baez,nan,Jackson Browne[N3]
211,2017,Journey,"Jonathan Cain, Aynsley Dunbar, Steve Perry, Gr...",Pat Monahan
212,2017,Pearl Jam,"Jeff Ament, Matt Cameron, Stone Gossard, Dave ...",David Letterman
213,2017,Tupac Shakur,nan,Snoop Dogg
214,2017,Yes,"Jon Anderson, Bill Bruford, Steve Howe, Tony K...",Geddy Lee[N3] and Alex Lifeson[N3]
215,2018,Bon Jovi,"Jon Bon Jovi, David Bryan, Hugh McDonald, Rich...",Howard Stern
216,2018,The Cars,"Elliot Easton, Greg Hawkes, David Robinson, Ri...",Brandon Flowers
217,2018,Dire Straits,"Alan Clark, Guy Fletcher, John Illsley, David ...",John Illsley[N4]
218,2018,The Moody Blues,"Graeme Edge, Justin Hayward, Denny Laine, John...",Ann Wilson[N3]
219,2018,Nina Simone,nan,Mary J. Blige
220,2019,The Cure,"Perry Bamonte, Jason Cooper, Michael Dempsey, ...",Trent Reznor[N2]
221,2019,Def Leppard,"Rick Allen, Vivian Campbell, Phil Collen, Stev...",Brian May[N3]
222,2019,Janet Jackson,nan,Janelle Mon√°e
223,2019,Stevie Nicks,nan,Harry Styles
224,2019,Radiohead,"Colin Greenwood, Jonny Greenwood, Ed O'Brien, ...",David Byrne[N3]
225,2019,Roxy Music,"Brian Eno, Bryan Ferry, Eddie Jobson, Andy Mac...",Simon Le Bon and John Taylor
226,2019,The Zombies,"Rod Argent, Paul Atkinson, Colin Blunstone, Hu...",Susanna Hoffs
227,2020,Depeche Mode,"Vince Clarke, Andy Fletcher, Dave Gahan, Marti...",Charlize Theron
228,2020,The Doobie Brothers,"Jeff ""Skunk"" Baxter, John Hartman, Michael Hos...",Luke Bryan
229,2020,Whitney Houston,[132],Alicia Keys
230,2020,Nine Inch Nails,"Alessandro Cortini, Robin Finck, Danny Lohner,...",Iggy Pop[N3]
231,2020,The Notorious B.I.G.,[135],Sean Combs
232,2020,T. Rex,"Marc Bolan, Steve Currie, Mickey Finn, and Bil...",Ringo Starr[N3]
233,2021,Foo Fighters[137],"Dave Grohl, Taylor Hawkins, Rami Jaffee, Nate ...",nan
234,2021,The Go-Go's[137],"Charlotte Caffey, Belinda Carlisle, Gina‚ÄØSchoc...",nan
235,2021,Jay-Z[137],nan,nan
236,2021,Carole King[137],nan,nan
237,2021,Todd Rundgren[137],nan,nan
238,2021,Tina Turner[137],nan,nan

In [14]:
df['Inducted By'] = df['Inducted By'].apply(lambda x: x.replace("["," "))

In [15]:
df['Inducted By'] = df['Inducted By'].apply(lambda x: x.replace("]"," "))

In [16]:
df['Inducted By'] = df['Inducted By'].apply(lambda x: x.replace("N2",""))
df['Inducted By'] = df['Inducted By'].apply(lambda x: x.replace("N3",""))

In [17]:
df['Inducted Members'] = df['Inducted Members'].apply(lambda x: x.replace("["," "))
df['Inducted Members'] = df['Inducted Members'].apply(lambda x: x.replace("]"," "))
df['Inducted Members'] = df['Inducted Members'].apply(lambda x: x.replace("22"," "))

In [18]:
df['Name'] = df['Name'].apply(lambda x: x.replace("["," "))
df['Name'] = df['Name'].apply(lambda x: x.replace("]"," "))
df['Name'] = df['Name'].apply(lambda x: x.replace("N2"," "))
df['Name'] = df['Name'].apply(lambda x: x.replace("137"," "))

In [19]:
df.head()

   Induction Year         Name Inducted Members       Inducted By
0            1986  Chuck Berry              nan  Keith Richards
1            1986  James Brown              nan   Steve Winwood
2            1986  Ray Charles              nan    Quincy Jones
3            1986    Sam Cooke              nan     Herb Alpert
4            1986  Fats Domino              nan      Billy Joel

In [20]:
# I counted the number of unique names of the inductees...however after doing so and realizing there are 239 unique names
# this makes sense as no one would be inducted more than 1x...
count_unique = df['Name'].nunique()

In [29]:
for a in df.Name:
    print(a)

Chuck Berry
James Brown
Ray Charles
Sam Cooke
Fats Domino
The Everly Brothers
Buddy Holly
Jerry Lee Lewis
Little Richard
Elvis Presley
The Coasters
Eddie Cochran
Bo Diddley
Aretha Franklin
Marvin Gaye
Bill Haley
B.B. King
Clyde McPhatter
Ricky Nelson
Roy Orbison
Carl Perkins
Smokey Robinson
Big Joe Turner
Muddy Waters
Jackie Wilson
The Beach Boys
The Beatles
The Drifters
Bob Dylan
The Supremes
Dion
Otis Redding
The Rolling Stones
The Temptations
Stevie Wonder
Hank Ballard
Bobby Darin
The Four Seasons
The Four Tops
The Kinks
The Platters
Simon & Garfunkel
The Who
LaVern Baker
The Byrds
John Lee Hooker
The Impressions
Wilson Pickett
Jimmy Reed
Ike & Tina Turner
Bobby "Blue" Bland
Booker T. & the M.G.'s
Johnny Cash
The Isley Brothers
The Jimi Hendrix Experience
Sam & Dave
The Yardbirds
Ruth Brown
Cream
Creedence Clearwater Revival
The Doors
Frankie Lymon & The Teenagers
Etta James
Van Morrison
Sly and the Family Stone
The Animals
The Band
Duane Eddy
The Grateful Dead
Elton John
John Lennon
Bob Marley
Rod Stewart
The Allman Brothers Band
Al Green
Janis Joplin
Led Zeppelin
Martha and the Vandellas
Neil Young
Frank Zappa
David Bowie
Gladys Knight & the Pips
Jefferson Airplane
Little Willie John
Pink Floyd
The Shirelles
The Velvet Underground
Bee Gees
Buffalo Springfield
Crosby, Stills & Nash
The Jackson 5
Joni Mitchell
Parliament-Funkadelic
The (Young) Rascals
Eagles
Fleetwood Mac
The Mamas & the Papas
Lloyd Price
Santana
Gene Vincent
Billy Joel
Curtis Mayfield
Paul McCartney
Del Shannon
Dusty Springfield
Bruce Springsteen
The Staple Singers
Eric Clapton
Earth, Wind & Fire
The Lovin' Spoonful
The Moonglows
Bonnie Raitt
James Taylor
Aerosmith
Solomon Burke
The Flamingos
Michael Jackson
Queen
Paul Simon
Steely Dan
Ritchie Valens
Isaac Hayes
Brenda Lee
Tom Petty and the Heartbreakers
Gene Pitney
Ramones
Talking Heads
AC/DC
The Clash
Elvis Costello & the Attractions
The Police
The Righteous Brothers
Jackson Browne
The Dells
George Harrison
Prince
Bob Seger
Traffic
ZZ Top
Buddy Guy
The O'Jays
The Pretenders
Percy Sledge
U2
Black Sabbath
Blondie
Miles Davis
Lynyrd Skynyrd
Sex Pistols
Grandmaster Flash and the Furious Five
R.E.M.
The Ronettes
Patti Smith
Van Halen
The Dave Clark Five
Leonard Cohen
Madonna
John Mellencamp
The Ventures
Jeff Beck
Little Anthony and the Imperials
Metallica
Run-DMC
Bobby Womack
ABBA
Genesis
Jimmy Cliff
The Hollies
The Stooges
Alice Cooper
Neil Diamond
Dr. John
Darlene Love
Tom Waits
Beastie Boys
The Blue Caps N1
The Comets N1
The Crickets N1
Donovan
The Famous Flames N1
Guns N' Roses
The Midnighters N1
The Miracles N1
Laura Nyro
Red Hot Chili Peppers
The Small Faces / Faces
Heart
Albert King
Randy Newman
Public Enemy
Rush
Donna Summer
Peter Gabriel
Hall & Oates
Kiss
Nirvana
Linda Ronstadt
Cat Stevens
The Paul Butterfield Blues Band
Joan Jett & the Blackhearts
Lou Reed 110
Green Day
Stevie Ray Vaughan and Double Trouble
Bill Withers
Cheap Trick
Chicago
Deep Purple
N.W.A
Steve Miller
Electric Light Orchestra
Joan Baez
Journey
Pearl Jam
Tupac Shakur
Yes
Bon Jovi
The Cars
Dire Straits
The Moody Blues
Nina Simone
The Cure
Def Leppard
Janet Jackson
Stevie Nicks
Radiohead
Roxy Music
The Zombies
Depeche Mode
The Doobie Brothers
Whitney Houston
Nine Inch Nails
The Notorious B.I.G.
T. Rex
Foo Fighters
The Go-Go's
Jay-Z
Carole King
Todd Rundgren
Tina Turner

In [21]:
print(count_unique)

239

In [22]:
print(df.nunique())

Induction Year       36
Name                239
Inducted Members    134
Inducted By         170
dtype: int64

In [23]:
df2 = df.set_index(['Induction Year', 'Name'], inplace=False)

In [24]:
df2

                                                                  Inducted Members  \
Induction Year Name
1986           Chuck Berry                                                     nan
               James Brown                                                     nan
               Ray Charles                                                     nan
               Sam Cooke                                                       nan
               Fats Domino                                                     nan
...                                                                            ...
2021           The Go-Go's       Charlotte Caffey, Belinda Carlisle, Gina‚ÄØSchoc...
               Jay-Z                                                           nan
               Carole King                                                     nan
               Todd Rundgren                                                   nan
               Tina Turner                                                     nan

                                      Inducted By
Induction Year Name
1986           Chuck Berry       Keith Richards
               James Brown        Steve Winwood
               Ray Charles         Quincy Jones
               Sam Cooke            Herb Alpert
               Fats Domino           Billy Joel
...                                           ...
2021           The Go-Go's                    nan
               Jay-Z                          nan
               Carole King                    nan
               Todd Rundgren                  nan
               Tina Turner                    nan

[239 rows x 2 columns]

In [25]:
df3 = df2.groupby(['Induction Year']).count()

In [26]:
df3.sort_values(by='Inducted By', ascending=False)

                Inducted Members  Inducted By
Induction Year
1987                          15           15
2012                          12           12
1986                          10           10
1990                           8            8
2001                           8            8
1993                           8            8
1994                           8            8
1997                           7            7
2019                           7            7
1999                           7            7
2004                           7            7
1996                           7            7
1995                           7            7
1992                           7            7
1991                           7            7
1998                           6            6
2020                           6            6
2017                           6            6
2015                           6            6
2014                           6            6
2013                           6            6
2021                           6            6
2002                           6            6
2000                           6            6
2008                           5            5
2007                           5            5
2010                           5            5
2011                           5            5
1989                           5            5
2006                           5            5
2005                           5            5
2003                           5            5
2016                           5            5
2018                           5            5
1988                           5            5
2009                           5            5

In [30]:
df.to_csv('rnrhof.csv')